### ISSUE TITLE
[1.20.1]Crash When install with LuckPerms

### ISSUE THREAD

**Issue by POCKET-CATTT** [Birbs-world/Better-Forge-Chat-Reborn#1]
[crash-2024-12-03_01.32.20-server.txt](https://github.com/user-attachments/files/17981818/crash-2024-12-03_01.32.20-server.txt)

**Comment by Birbs-world** [comment]
Ahh yes forgot about this issue haha, fix is in progress

**Comment by POCKET-CATTT** [comment]
Thanks you for the hotfix
