### ISSUE TITLE
Single player support

### ISSUE THREAD

**Issue by POCKET-CATTT** [Birbs-world/Better-Forge-Chat-Reborn#2]
[crash-2024-12-03_03.12.19-server.txt](https://github.com/user-attachments/files/17982783/crash-2024-12-03_03.12.19-server.txt)

**Comment by Birbs-world** [comment]
can you post your server log? also what version of luckperms are you running?

**Comment by POCKET-CATTT** [comment]
sure wait a sec

**Comment by POCKET-CATTT** [comment]
[latest.log](https://github.com/user-attachments/files/17982928/latest.log)
LuckPerms-1.20.1-5.4.102

**Comment by POCKET-CATTT** [comment]
[latest.log](https://github.com/user-attachments/files/17982967/latest.log)

**Comment by Birbs-world** [comment]
is this when starting or joining the server

**Comment by Birbs-world** [comment]
ahh, better forge chat is designed to be used with a Dedicated Server Configuration have tested this way and it works without issue (see screenshot)
BFCR currently doesn't have Full support for Single Player hence the reason of your crash. do you intend to use BFCR on a Server or Just in singleplayer?

![Image](https://github.com/user-attachments/assets/a8f56805-b6eb-446e-bd70-5e0ac0162ffd)

**Comment by POCKET-CATTT** [comment]
Both 
Currently i was testing it with other mod in singleplayer to see if it will cause crash

**Comment by Birbs-world** [comment]
It is only need on the Dedicated server side, its not needed on the client. can you please test on the dedicated server, I've marked this as a todo enhancement for use in singleplayer.

**Comment by POCKET-CATTT** [comment]
That will take me 1 hour to reboot and update my linux server
i will test it tomorrow

**Comment by Birbs-world** [comment]
ok

**Comment by POCKET-CATTT** [comment]
Also i notice ChatImage seems conflict with BFCR

**Comment by POCKET-CATTT** [comment]
https://www.curseforge.com/minecraft/mc-mods/chatimage

**Comment by Birbs-world** [comment]
Other chat modification mods are assumed incompatible until proven otherwise, there will always be conflicts with any mod that interacts with the same thing as another mod. Integrations/support needs to be added to them specifically for the conflicts to be resolved.

**Comment by POCKET-CATTT** [comment]
seems work greatly

**Comment by Birbs-world** [comment]
Single player support has been added.

 LuckPerms disables itsself when loading on client side hence the not loaded crash.

Bfcr will now disable the luckperms integration when loading single player regardless of config settings.
